module.exports = {
    UNIQUE_VIOLATION: 'unique violation',
    MISSING_TOKEN: 'MISSING_TOKEN',
    MISSING_REFRESH_TOKEN: 'MISSING_REFRESH_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',

    EXPIRED_ACTIVATION_CODE: 'EXPIRED_ACTIVATION_CODE',
    INVALID_ACTIVATION_CODE: 'INVALID_ACTIVATION_CODE',

    ACTION_OF_ANOTHER_USER: 'ACTION_OF_ANOTHER_USER',
    NOT_PARENT_IN_FAMILY: 'NOT_PARENT_IN_FAMILY',
    NOT_PARENT_OF_CHILD: 'NOT_PARENT_OF_CHILD',

    BOTH_PARENTS_EXIST: 'BOTH_PARENTS_EXIST'
};